Models/Carrinho.cs
namespace PWEBTP.Models
{
    public class Carrinho
    {
        public List<CarrinhoItem> items { get; set; } = new List<CarrinhoItem>();

        public void AddItem(Carro carro, int qtd)
        {
            var item = items.FirstOrDefault(i => i.CarroId == carro.Id);

            if (item != null)
            {
                item.Quantidade += qtd;
                return;
            }

            items.Add(new CarrinhoItem
            {
                CarroId = carro.Id,
                CarroNome = carro.Name,
                PrecoUnit = carro.Preco,
                Quantidade = qtd
            });
        }

        public void RemoveItem(Carro curso) => items.RemoveAll(i => i.CarroId == curso.Id);
        public int TotalItems() => items.Sum(i => i.Quantidade);
        public decimal Total() => items.Sum(i => i.PrecoUnit * i.Quantidade);
        public void Clear() => items.Clear();
    }
}

Controllers/CarrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEBTP.Data;
using PWEBTP.Models;
using PWEBTP.Models.Helpers;
using PWEBTP.Models.ViewModels;

namespace PWEBTP.Controllers
{
    public class CarrosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CarrosController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Carroes
        public async Task<IActionResult> Index(bool? disponivel)
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categorias.ToList(), "Id", "Name");

            if(disponivel != null)
            {
                if(disponivel == true)
                {
                    ViewData["Title"] = "Lista de Carros Ativos";
                }
                else
                {
                    ViewData["Title"] = "Lista de Carros Inativos";
                }
                return View(await _context.Carros.Include("Categoria").Where(c => c.Disponivel == disponivel).ToListAsync());
            }
            ViewData["Title"] = "Lista de Carros"; 
            return View(await _context.Carros.Include("Categoria").ToListAsync());
        }

        // GET: Carroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.Include("Categoria").FirstOrDefaultAsync(m => m.Id == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // GET: Carroes/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["ListaDeCategorias"] = new SelectList(_context.Categorias.ToList(), "Id", "Name");
            return View();
        }

        // POST: Carroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Preco,Descricao,Disponivel,EmDestaque,CategoriaId")] Carro carro)
        {
            ViewData["ListaDeCategorias"] = new SelectList(_context.Categorias.ToList(), "Id", "Name");

            ModelState.Remove(nameof(carro.Categoria));
            if (ModelState.IsValid)
            {
                _context.Add(carro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.FindAsync(id);
            if (carro == null)
            {
                return NotFound();
            }
            return View(carro);
        }

        // POST: Carroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Funcionario, Gestor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Preco,Descricao,Disponivel,EmDestaque")] Carro carro)
        {
            if (id != carro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarroExists(carro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        [HttpPost]
        public async Task<IActionResult> Search([Bind("TextoAPesquisar")]
            PesquisaCarroViewModel pesquisaCarro, int CategoriaId)
        {
            if (string.IsNullOrWhiteSpace(pesquisaCarro.TextoAPesquisar))
            {
                pesquisaCarro.ListaDeCarros = await _context.Carros.Include("Categoria").
                    Where(c => c.CategoriaId == CategoriaId).ToListAsync();
            }
            else
            {

                pesquisaCarro.ListaDeCarros = await _context.Carros.Include("Categoria").Where(
                    c => c.Name.Contains(pesquisaCarro.TextoAPesquisar)
                    || c.Descricao.Contains(pesquisaCarro.TextoAPesquisar)
                    || c.CategoriaId == CategoriaId
                    ).ToListAsync();

            }
            pesquisaCarro.NumResultados = pesquisaCarro.ListaDeCarros.Count;

            ViewData["Title"] = "Os nossos Carros";

            return View(pesquisaCarro);
        }

        public async Task<IActionResult> Carrinho()
        {
            var carrinhoDeCompras = HttpContext.Session.GetJson<Carrinho>("CarrinhoDeCompras") ?? new Carrinho();
            return View(carrinhoDeCompras);
        }
  
        public IActionResult Comprar(int? id)
        {

            var carro = _context.Carros.Where(u => u.Id == id).FirstOrDefault();

            if (carro == null)
                return RedirectToAction(nameof(Index));

            var CarrinhoDeCompras = HttpContext.Session.GetJson<Carrinho>("CarrinhoDeCompras") ?? new Carrinho();

            CarrinhoDeCompras.AddItem(carro, 1);

            HttpContext.Session.SetJson("CarrinhoDeCompras", CarrinhoDeCompras);

            return RedirectToAction("Carrinho");
        }

        public async Task<IActionResult> AlterarQuantidadeCarrinhoItem(int? carroId, int? quantidade)
        {
            if (carroId == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.Include("Categoria")
                .FirstOrDefaultAsync(m => m.Id == carroId);
           //var carro = await _context.Carros.Include(c => c.Categoria).FirstOrDefaultAsync(c => c.Id == carroId);

            if (carro == null)
            {
                return NotFound();
            }

            var carrinhoDeCompras = HttpContext.Session.GetJson<Carrinho>("CarrinhoDeCompras") ?? new Carrinho();
            //carrinhoDeCompras.AddItem(carro, quantidade.GetValueOrDefault());
            var item = carrinhoDeCompras.items.First(i => i.CarroId == carroId);
            if (item == null)
            {
                return NotFound();
            }

            item.Quantidade += quantidade.GetValueOrDefault();
            if (item.Quantidade <= 0)
            {
                return await RemoverCarrinhoItem(carroId);
            }

            HttpContext.Session.SetJson("CarrinhoDeCompras", carrinhoDeCompras);
            return RedirectToAction(nameof(Carrinho));
        }

        public async Task<IActionResult> RemoverCarrinhoItem(int? carroId)
        {
            if (carroId == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.Include("Categoria")
                .FirstOrDefaultAsync(m => m.Id == carroId);
            if (carro == null)
            {
                return NotFound();
            }

            var carrinhoDeCompras = HttpContext.Session.GetJson<Carrinho>("CarrinhoDeCompras") ?? new Carrinho();
            carrinhoDeCompras.RemoveItem(carro);

            HttpContext.Session.SetJson("CarrinhoDeCompras", carrinhoDeCompras);
            return RedirectToAction(nameof(Carrinho));
        }


        // POST: Carroes/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Carros == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Carros'  is null.");
            }
            var carro = await _context.Carros.FindAsync(id);
            if (carro != null)
            {
                _context.Carros.Remove(carro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarroExists(int id)
        {
            return _context.Carros.Any(e => e.Id == id);
        }
    }
}

Controllers/GestorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEBTP.Data;
using PWEBTP.Models;

namespace PWEBTP.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GestorsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public GestorsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Gestors
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Gestores.Include(g => g.Empresa);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Gestors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Gestores == null)
            {
                return NotFound();
            }

            var gestor = await _context.Gestores
                .Include(g => g.Empresa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gestor == null)
            {
                return NotFound();
            }

            return View(gestor);
        }

        // GET: Gestors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Gestores == null)
            {
                return NotFound();
            }

            var gestor = await _context.Gestores.FindAsync(id);
            if (gestor == null)
            {
                return NotFound();
            }
            return View(gestor);
        }

        // POST: Gestors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,EmpresaId")] Gestor gestor)
        {
            if (id != gestor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gestor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GestorExists(gestor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Id", gestor.EmpresaId);
            return View(gestor);
        }

        // GET: Gestors/Delete/5

        public IActionResult Create()
        {
            ViewData["EmpresaId"] = new SelectList(_context.Empresas.ToList(), "Id", "Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,EmpresaId")] Gestor gestor)
        {
            ViewData["EmpresaId"] = new SelectList(_context.Empresas.ToList(), "Id", "Name");
            
            ModelState.Remove(nameof(gestor.Funcionarios));
            ModelState.Remove(nameof(gestor.Empresa));
            ModelState.Remove(nameof(gestor.User));
            if (ModelState.IsValid)
            {
                await CriaConta(gestor);
               
                _context.Add(gestor);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gestor);
        }


        public async Task CriaConta(Gestor gestor)
        {
            var empresa = _context.Empresas.Find(gestor.EmpresaId);

            var GestorConta = new ApplicationUser
            {
                UserName = gestor.Name.ToLower() + "@" + empresa.Name.ToLower() + ".pt",
                Email = gestor.Name.ToLower() + "@" + empresa.Name.ToLower() + ".pt",
                PrimeiroNome = empresa.Name,
                UltimoNome = gestor.Name,
                EmailConfirmed = true,
                PhoneNumberConfirmed = true
            };

            var user = await _userManager.FindByEmailAsync(GestorConta.Email);
            if(user == null)
            {
                await _userManager.CreateAsync(GestorConta, "Is3C..00");
                await _userManager.AddToRoleAsync(GestorConta, Roles.Gestor.ToString());
                gestor.User = GestorConta;
                await _context.SaveChangesAsync();
            }
        }
    
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Gestores == null)
            {
                return NotFound();
            }

            var gestor = await _context.Gestores
                .Include(g => g.Empresa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gestor == null)
            {
                return NotFound();
            }

            return View(gestor);
        }

        // POST: Gestors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Gestores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Gestores'  is null.");
            }

            var gestor = await _context.Gestores.FindAsync(id);
            if (gestor != null)
            {
                await DeleteConta(gestor);
                _context.Gestores.Remove(gestor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task DeleteConta(Gestor gestor)
        {
            var empresa = _context.Empresas.Find(gestor.EmpresaId);

            var user = await _userManager.FindByEmailAsync(gestor.Name.ToLower() + "@" + empresa.Name.ToLower() + ".pt");

            var roles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, roles);

            await _userManager.DeleteAsync(user);
        } 

        private bool GestorExists(int id)
        {
          return _context.Gestores.Any(e => e.Id == id);
        }
    }
}

Views/Shared/QuickSearchPartial.cshtml
@using (Html.BeginForm("Search", "Carros", FormMethod.Post))
{
    <div class="form-inline d-flex">
        <input type="text" name="TextoAPesquisar" id="TextoAPesquisar"
           placeholder="Pesquisar um carro" class="form-control form-control-sm" />
        <button type="submit" class="btn btn-default ms-2 me-2">
            <svg bootstrap-icon="Search" class="text-warning" width="24" height="24"
             aria-label="Search"></svg>
        </button>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car Rental TP 22/23</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/carousel.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/MyStyleSheet.css" asp-append-version="true" />
</head>
<body class="d-flex h-100 text-center  bg-white p-0 m-0">
    <div class="cover-container d-flex w-100 h-100 p-0 mx-auto flex-column">
        <header class="p-7 text-white">
            <div class="container">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark mb-3 fixed-top" style="background: rgba(0, 0, 0, .5);">
                    <div class="container">
                        <a class="navbar-brand text-warning" href="#"><svg bootstrap-icon="SignTurnRightFill" class="text-warning" width="48" height="48" aria-label="SignTurnRightFill"></svg> <strong>Car Rental</strong></a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">INÍCIO</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Contactos">CONTACTOS</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        CARROS
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="Carros" asp-action="Index">CARROS</a>
                                        </li>
                                        
                                        @if (User.IsInRole("Gestor"))
                                        {
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Carros" asp-action="GraficoVendas">Graficos Vendas</a>
                                            </li>
                                        }
                                    
                                    </ul>
                                </li>
                                
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            RESERVAS
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Reservas" asp-action="Index">Todos os Agendamentos</a>
                                            </li>
                                            @if (User.Identity.IsAuthenticated)
                                            {
                                                <li><hr class="dropdown-divider"></li>
                                                <li>
                                                    <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Pedido">Pedido de Agendamento</a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="MeusAgendamentos">Meus Agendamentos</a>
                                                </li>
                                            }
                                        </ul>
                                    </li>

                                    @if(User.IsInRole("Admin"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="Empresas" asp-action="Index">EMPRESAS</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="Gestors" asp-action="Index">GESTORES</a>
                                        </li>
                                    }

                                    @if (User.IsInRole("Gestor") || User.IsInRole("Admin"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-white" asp-area="" asp-controller="Funcionarios" asp-action="Index">FUNCIONARIOS</a>
                                        </li>
                                }
                                
                            </ul>
                            <partial name="_carrinho" />
                            <partial name="QuickSearchPartial" />
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <main class="px-0 mx-0">
            @RenderBody()
        </main>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2023 - Car Rental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car Rental TP 22/23</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/carousel.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/MyStyleSheet.css" asp-append-version="true" />
</head>
<body class="d-flex h-100 text-center  bg-white p-0 m-0">
    <div class="cover-container d-flex w-100 h-100 p-0 mx-auto flex-column">
        <header class="p-7 text-white">
            <div class="container">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark mb-3 fixed-top" style="background: rgba(0, 0, 0, .5);">
                    <div class="container">
                        <a class="navbar-brand text-warning" href="#"><svg bootstrap-icon="SignTurnRightFill" class="text-warning" width="48" height="48" aria-label="SignTurnRightFill"></svg> <strong>Car Rental</strong></a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">INÍCIO</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Contactos">CONTACTOS</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        CARROS
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li>
                                            <a class="dropdown-item" asp-area="" asp-controller="Carros" asp-action="Index">CARROS</a>
                                        </li>
                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Carros" asp-action="GraficoVendas">Graficos Vendas</a>
                                            </li>
                                        }
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Categorias" asp-action="Index">CATEGORIAS</a>
                                </li>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            RESERVAS
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li>
                                                <a class="dropdown-item" asp-area="" asp-controller="Reservas" asp-action="Index">RESERVAS</a>
                                            </li>
                                            @if (User.Identity.IsAuthenticated)
                                            {
                                                <li><hr class="dropdown-divider"></li>
                                                <li>
                                                    <a class="dropdown-item" asp-area="" asp-controller="Reservas" asp-action="">PEDIDOS</a>
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                }
                            </ul>
                            </ul>
                            <partial name="_carrinho" />
                            <partial name="QuickSearchPartial" />
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <main class="container mt-5 pt-5 text-start">
            @RenderBody()
        </main>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2023 - Car Rental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_carrinho.cshtml
@using PWEBTP.Models.Helpers
@{
    var CarrinhoDeCompras = Context.Session.GetJson<Carrinho>("CarrinhoDeCompras") ??
           new Carrinho();
    int qtd = CarrinhoDeCompras == null ? 0 : CarrinhoDeCompras.items.Count();
}
<div class="form-inline d-flex ">
    <span class="badge badge-dark fs-6 ">@qtd</span>
    <strong>
        <svg bootstrap-icon="Cart"
             class="text-white me-2" width="24" height="24"
             aria-label="Search"></svg>
    </strong>
</div>