Models/Carrinho.cs
namespace PWEBTP.Models
{
    public class Carrinho
    {
        public List<CarrinhoItem> items { get; set; } = new List<CarrinhoItem>();

        public void AddItem(Carro carro, int qtd)
        {
            var item = items.FirstOrDefault(i => i.CarroId == carro.Id);

            if (item != null)
            {
                item.Quantidade += qtd;
                return;
            }

            items.Add(new CarrinhoItem
            {
                CarroId = carro.Id,
                CarroNome = carro.Name,
                PrecoUnit = carro.Preco,
                Quantidade = qtd
            });
        }

        public void RemoveItem(Carro curso) => items.RemoveAll(i => i.CarroId == curso.Id);
        public int TotalItems() => items.Sum(i => i.Quantidade);
        public decimal Total() => items.Sum(i => i.PrecoUnit * i.Quantidade);
        public void Clear() => items.Clear();
    }
}

Models/Carro.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PWEBTP.Models
{
    public class Carro
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Preco { get; set; }
        public string Descricao { get; set; }
        public bool Disponivel { get; set; }
        public bool EmDestaque { get; set; }
        public int Kilometros { get; set; }

        //Tem uma categoria
        [ForeignKey("Categoria")]
        public int CategoriaId { get; set; }
        public Categoria Categoria { get; set; }

    }
}

Controllers/CarrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEBTP.Data;
using PWEBTP.Models;
using PWEBTP.Models.Helpers;
using PWEBTP.Models.ViewModels;

namespace PWEBTP.Controllers
{
    public class CarrosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CarrosController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Carroes
        public async Task<IActionResult> Index(bool? disponivel)
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categorias.ToList(), "Id", "Name");

            if(disponivel != null)
            {
                if(disponivel == true)
                {
                    ViewData["Title"] = "Lista de Carros Ativos";
                }
                else
                {
                    ViewData["Title"] = "Lista de Carros Inativos";
                }
                return View(await _context.Carros.Include("Categoria").Where(c => c.Disponivel == disponivel).ToListAsync());
            }
            ViewData["Title"] = "Lista de Carros"; 
            return View(await _context.Carros.Include("Categoria").ToListAsync());
        }

        // GET: Carroes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.Include("Categoria").FirstOrDefaultAsync(m => m.Id == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // GET: Carroes/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["ListaDeCategorias"] = new SelectList(_context.Categorias.ToList(), "Id", "Name");
            return View();
        }

        // POST: Carroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Preco,Descricao,Disponivel,EmDestaque,CategoriaId")] Carro carro)
        {
            ViewData["ListaDeCategorias"] = new SelectList(_context.Categorias.ToList(), "Id", "Name");

            ModelState.Remove(nameof(carro.Categoria));
            if (ModelState.IsValid)
            {
                _context.Add(carro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carroes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.FindAsync(id);
            if (carro == null)
            {
                return NotFound();
            }
            return View(carro);
        }

        // POST: Carroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Funcionario, Gestor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Preco,Descricao,Disponivel,EmDestaque")] Carro carro)
        {
            if (id != carro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarroExists(carro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carroes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        [HttpPost]
        public async Task<IActionResult> Search([Bind("TextoAPesquisar")]
            PesquisaCarroViewModel pesquisaCarro, int CategoriaId)
        {
            if (string.IsNullOrWhiteSpace(pesquisaCarro.TextoAPesquisar))
            {
                pesquisaCarro.ListaDeCarros = await _context.Carros.Include("Categoria").
                    Where(c => c.CategoriaId == CategoriaId).ToListAsync();
            }
            else
            {

                pesquisaCarro.ListaDeCarros = await _context.Carros.Include("Categoria").Where(
                    c => c.Name.Contains(pesquisaCarro.TextoAPesquisar)
                    || c.Descricao.Contains(pesquisaCarro.TextoAPesquisar)
                    || c.CategoriaId == CategoriaId
                    ).ToListAsync();

            }
            pesquisaCarro.NumResultados = pesquisaCarro.ListaDeCarros.Count;

            ViewData["Title"] = "Os nossos Carros";

            return View(pesquisaCarro);
        }

        public async Task<IActionResult> Carrinho()
        {
            var carrinhoDeCompras = HttpContext.Session.GetJson<Carrinho>("CarrinhoDeCompras") ?? new Carrinho();
            return View(carrinhoDeCompras);
        }
  
        public IActionResult Comprar(int? id)
        {

            var carro = _context.Carros.Where(u => u.Id == id).FirstOrDefault();

            if (carro == null)
                return RedirectToAction(nameof(Index));

            var CarrinhoDeCompras = HttpContext.Session.GetJson<Carrinho>("CarrinhoDeCompras") ?? new Carrinho();

            CarrinhoDeCompras.AddItem(carro, 1);

            HttpContext.Session.SetJson("CarrinhoDeCompras", CarrinhoDeCompras);

            return RedirectToAction("Carrinho");
        }

        public async Task<IActionResult> AlterarQuantidadeCarrinhoItem(int? carroId, int? quantidade)
        {
            if (carroId == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.Include("Categoria")
                .FirstOrDefaultAsync(m => m.Id == carroId);
           //var carro = await _context.Carros.Include(c => c.Categoria).FirstOrDefaultAsync(c => c.Id == carroId);

            if (carro == null)
            {
                return NotFound();
            }

            var carrinhoDeCompras = HttpContext.Session.GetJson<Carrinho>("CarrinhoDeCompras") ?? new Carrinho();
            //carrinhoDeCompras.AddItem(carro, quantidade.GetValueOrDefault());
            var item = carrinhoDeCompras.items.First(i => i.CarroId == carroId);
            if (item == null)
            {
                return NotFound();
            }

            item.Quantidade += quantidade.GetValueOrDefault();
            if (item.Quantidade <= 0)
            {
                return await RemoverCarrinhoItem(carroId);
            }

            HttpContext.Session.SetJson("CarrinhoDeCompras", carrinhoDeCompras);
            return RedirectToAction(nameof(Carrinho));
        }

        public async Task<IActionResult> RemoverCarrinhoItem(int? carroId)
        {
            if (carroId == null || _context.Carros == null)
            {
                return NotFound();
            }

            var carro = await _context.Carros.Include("Categoria")
                .FirstOrDefaultAsync(m => m.Id == carroId);
            if (carro == null)
            {
                return NotFound();
            }

            var carrinhoDeCompras = HttpContext.Session.GetJson<Carrinho>("CarrinhoDeCompras") ?? new Carrinho();
            carrinhoDeCompras.RemoveItem(carro);

            HttpContext.Session.SetJson("CarrinhoDeCompras", carrinhoDeCompras);
            return RedirectToAction(nameof(Carrinho));
        }


        // POST: Carroes/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Carros == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Carros'  is null.");
            }
            var carro = await _context.Carros.FindAsync(id);
            if (carro != null)
            {
                _context.Carros.Remove(carro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarroExists(int id)
        {
            return _context.Carros.Any(e => e.Id == id);
        }
    }
}

Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PWEBTP.Data;
using PWEBTP.Data.Migrations;
using PWEBTP.Models;

namespace PWEBTP.Controllers
{
    public class ReservasController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public ReservasController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Reservas
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Reservas.Include(r => r.Cliente).Include(r => r.carro);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reservas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Reservas == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas
                .Include(r => r.Cliente)
                .Include(r => r.carro)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // GET: Reservas/Create
        public IActionResult Create()
        {
            ViewData["CarroId"] = new SelectList(_context.Carros, "Id", "Name");
            return View();
        }

        // POST: Reservas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DataInicio,DataFim,CarroId")] Reserva reserva)
        {
            var applicationUser = await _userManager.GetUserAsync(User);
            var cliente = await _context.Clientes.FirstOrDefaultAsync(c => c.ApplicationUser == applicationUser);

            ModelState.Remove(nameof(reserva.Cliente));
            ModelState.Remove(nameof(reserva.Funcionario));
            ModelState.Remove(nameof(reserva.carro));

            if (ModelState.IsValid)
            {
                _context.Add(reserva);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["CarroId"] = new SelectList(_context.Carros, "Id", "Name", reserva.CarroId);
            return View(reserva);
        }

        // GET: Reservas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Reservas == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas.FindAsync(id);
            if (reserva == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", reserva.ClienteId);
            ViewData["CarroId"] = new SelectList(_context.Carros, "Id", "Id", reserva.CarroId);
            return View(reserva);
        }

        // POST: Reservas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DataInicio,DataFim,Entregue,Aceite,KmsFinais,CarroId,FuncionarioId,ClienteId")] Reserva reserva)
        {
            if (id != reserva.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reserva);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservaExists(reserva.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", reserva.ClienteId);
            ViewData["CarroId"] = new SelectList(_context.Carros, "Id", "Id", reserva.CarroId);
            return View(reserva);
        }

        // GET: Reservas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Reservas == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas
                .Include(r => r.Cliente)
                .Include(r => r.carro)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }

        // POST: Reservas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Reservas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Reservas'  is null.");
            }
            var reserva = await _context.Reservas.FindAsync(id);
            if (reserva != null)
            {
                _context.Reservas.Remove(reserva);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservaExists(int id)
        {
          return _context.Reservas.Any(e => e.Id == id);
        }
    }
}

Views/Carros/Carrinho.cshtml
@model PWEBTP.Models.Carrinho

@{
    ViewData["Title"] = "Carrinho";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h1>Carrinho de compras</h1>
Items no carrinho: <span class="badge bg-secondary">@Model.Total()</span>
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>Item</th>
            <th>Preço Unitário</th>
            <th>Quantidade</th>
            <th>Sub-total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Total() == 0)
        {
            <tr>
                <td colspan="4" class="text-danger">Não existem produtos no carrinho</td>
            </tr>
        }
        @foreach (var item in Model.items)
        {
            <tr>
                <th>@item.CarroNome</th>
                <th>@item.PrecoUnit</th>
                <th>@item.Quantidade</th>
                <th>
                    <a asp-action="AlterarQuantidadeCarrinhoItem" asp-route-carroId="@item.CarroId" asp-route-quantidade="-1">-</a> |
                    <a asp-action="AlterarQuantidadeCarrinhoItem" asp-route-carroId="@item.~CarroId" asp-route-quantidade="1">+</a> |
                    <a asp-action="RemoverCarrinhoItem" asp-route-cursoId="@item.CarroId" onclick="return confirm('Tem a certeza que deseja remover?')">Remover</a>
                </th>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.Total()</td>
        </tr>
    </tfoot>
</table>
<div class="row">
    <div class="col-12 text-end ">
        <a class="btn btn-success" asp-area="" asp-controller="Carros" asp-action="Index">Continuar a Comprar</a>
        <a href="#" class="btn btn-success">Checkout</a>
    </div>
</div>

Views/Carros/Create.cshtml
@model PWEBTP.Models.Carro

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h1>Create</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disponivel" /> @Html.DisplayNameFor(model => model.Disponivel)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EmDestaque" /> @Html.DisplayNameFor(model => model.EmDestaque)
                </label>
            </div>

            <div class="form-group">
                <label asp-for="CategoriaId" class="control-label"></label>

                <select asp-for="CategoriaId"
                        asp-items="ViewBag.ListaDeCategorias"
                        class="form-control">
                </select>
                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carros/Delete.cshtml
@model PWEBTP.Models.Carro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disponivel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disponivel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmDestaque)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmDestaque)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Carros/Details.cshtml
@model PWEBTP.Models.Carro

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disponivel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disponivel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmDestaque)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmDestaque)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Carros/Index.cshtml
@model IEnumerable<Carro>

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h1>
    @ViewData["Title"]
</h1>

<form method="post" action="Carros/Search">
    <label for="TextoAPesquisar">Pesquisa de carros:</label>
    <input type="text" id="TextoAPesquisar" name="TextoAPesquisar"
           placeholder="texto a procurar" />
    <select name="CategoriaId" asp-items="ViewBag.CategoriaId"></select>
    <button id="botaoPesquisa" type="submit" class="btn btn-default">
        🔍
    </button>
</form>

<p>
    <a asp-action="Create">Adicionar Carro</a>
</p>
<a asp-action="Index">Todos</a>
<a asp-action="Index" asp-route-disponivel="true">Activos</a>
<a asp-action="Index" asp-route-disponivel="false">Inativos</a>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>
                <p>Nome Carro</p>
            </th>
            <th>
                <p>Disponivel</p>
            </th>
            <th>
                <p>Categoria</p>
            </th>
            <th>
                <p>Kilometros</p>
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Disponivel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kilometros)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Apagar</a> |
                    <a asp-area="" asp-controller="Reservas" asp-action="Create">Comprar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Carros/Search.cshtml
@using PWEBTP.Models.ViewModels
@model PesquisaCarroViewModel

@{
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<h1>
    @ViewData["Title"]
</h1>

<div class="container bg-white">
    @if (!(string.IsNullOrEmpty(Model.TextoAPesquisar)))
    {
        <p>Resultado da pesquisa por "@Model.TextoAPesquisar":</p>

        @if (Model.NumResultados == 0)
        {
            <p class="alert alert-warning">
                Não foi possível encontrar carros com os dados introduzidos. Por favor, reveja a sua
                pesquisa
            </p>
        }
    }
    else
    {
        <p>Existe(m) @Model.NumResultados carro(s) disponiveis</p>
    }
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        @foreach (var item in Model.ListaDeCarros)
        {
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        @if (string.IsNullOrWhiteSpace(Model.TextoAPesquisar))
                        {
                            <h4 class="my-0 fw-normal">
                                @Html.DisplayFor(modelItem => item.Name)
                                (@Html.DisplayFor(modelItem => item.Categoria.Name))
                            </h4>
                        }
                        else
                        {
                            <h4 class="my-0 fw-normal">
                                @Html.Raw(item.Name.ToString().ToLower().Replace(
                        Model.TextoAPesquisar.ToLower(),
                        "<span class=\"bg-warning\">"+Model.TextoAPesquisar+"</span>"))
                                (@Html.DisplayFor(modelItem => item.Categoria.Name))
                            </h4>
                        }
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">

                            @Html.DisplayFor(modelItem => item.Preco)
                            <small class="text-muted fw-light"></small>
                        </h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            @if (string.IsNullOrWhiteSpace(Model.TextoAPesquisar))
                            {
                                <li class="my-0 fw-normal">
                                    @Html.DisplayFor(modelItem => item.Descricao)
                                </li>
                            }
                            else
                            {
                                <li class="my-0 fw-normal">
                                    @Html.Raw(item.Descricao.ToString().ToLower().Replace(
                            Model.TextoAPesquisar.ToLower(),
                            "<span class=\"bg-warning\">"+Model.TextoAPesquisar+"</span>"))
                                </li>
                            }
                        </ul>
                        <a class="btn btn-lg btn-outline-primary"
                       asp-controller="Carros" asp-action="Details" asp-route-id="@item.Id">
                            Saber
                            mais
                        </a>
                        <a class="btn btn-lg btn-success"
                       asp-controller="Carros" asp-action="Comprar" asp-route-id="@item.Id">
                            Comprar
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>